services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game_deal
    networks:
      - gamedeal_network
    volumes:
      - ./compose/mysql:/docker-entrypoint-initdb.d

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - gamedeal_network

networks:
  gamedeal_network:
    name: gamedeal
    driver: bridge
