name: CI/CD

on:
  push:

jobs:
  backend:
    secrets: inherit
    uses: ./.github/workflows/backend.yml

  frontend:
    secrets: inherit
    needs: [backend]
    uses: ./.github/workflows/frontend.yml
