name: CI

on:
  push:

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
  frontend:
    uses: ./.github/workflows/frontend.yml
  coverage:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./coverage
      - uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: ./coverage
