name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build

  test:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup MySQL 8
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'game_price_tracker_test'
          mysql root password: 'root'
      - name: Setup Redis 7
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 7
      - run: npm ci
      - run: npm run test:cov
        env:
          test: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run lint

  validate_swagger_file:
    name: 🧪 Validate Swagger File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: ./src/modules/api/docs/swagger.yaml

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [build, test, validate_swagger_file]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.3.2
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
