name: CI/CD

on:
  push:

jobs:
  backend:
    name: Backend
    secrets: inherit
    uses: ./.github/workflows/backend.yml

  frontend:
    name: Frontend
    secrets: inherit
    needs: [backend]
    uses: ./.github/workflows/frontend.yml

  coverage:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: download backend coverage
        uses: actions/download-artifact@v3
        with:
          name: backend_coverage
          path: coverage/backend
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: download frontend coverage
        uses: actions/download-artifact@v3
        with:
          name: frontend_coverage
          path: coverage/frontend
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: coverage
