name: CI/CD

on:
  push:

jobs:
  backend:
    name: Backend CI
    secrets: inherit
    uses: ./.github/workflows/backend.yml

  frontend:
    name: Frontend CI
    secrets: inherit
    needs: [backend]
    uses: ./.github/workflows/frontend.yml

  docker:
    name: Build and Publish Docker Container
    needs: [backend, frontend]
    secrets: inherit
    uses: ./.github/workflows/docker.yml

  coverage:
    name: Upload Coverage
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Download Backend Coverage
        uses: actions/download-artifact@v8
        with:
          name: backend_coverage
          path: coverage/backend
          github-token: ${{ secrets.GH_PAT }}
      - name: Download Frontend Coverage
        uses: actions/download-artifact@v8
        with:
          name: frontend_coverage
          path: coverage/frontend
          github-token: ${{ secrets.GH_PAT }}
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: coverage
